name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 16
        architecture:
          - x64
    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ matrix.node_version }}'
      - run: ls
      - run: cat README.md
      - run: vim version.json
      - run: i
      - run: Hello
      - run: q
      - run: :wq
      - run: ls
