# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 12
    - run: echo `date +"%Y-%m-%d %H:%M:%S"` >> update.log
    - run: git status
    - run: git fetch
    - run: git pull
    - run: git config --global user.email "i@kohai.top"
    - run: git config --global user.name "kohai"
    - run: git add . && git commit -m "update"
    - run: git push && git status
